### ISSUE TITLE
redirect to uri

### ISSUE THREAD

**Issue by tbba** [mike-anthony/ProcessJumplinks#6]
latest dev PW latest dev JumpLinks:

Redirecting an image 
cmd/system/files/support/mailsafa57558l5.jpg

to
https://www.domain.de/site/templates/rey-transp.png

returns:
 SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'rootparent'

**Comment by mike-anthony** [comment]
Hi Carl,

I am indeed able to reproduce that error, and it appears it has something to do with strings not being enclosed properly. The issue more than likely arose when I moved over to prepared statements. That said, I am new to prepared statements in PDO, and so I may have missed something.

Will look into a fix shortly - thanks for bringing this up. :+1:

**Comment by mike-anthony** [comment]
Ah, it appears the error is coming from the following line, and is an oversight. Will have it fixed within a few hours.

**Comment by mike-anthony** [comment]
I have fixed the issue, but I'd like to test properly to make sure it hasn't broken anything.

Essentially, the problem came about because I wasn't checking to see if an absolute URL was being used when determining if the destination path mapped to an existing page. So, it was sending the full URL to `$pages->get`, which caused the SQL error.

I've now implemented the check on my side, and it those URLs are now being accepted. Once I've done my testing, I'll commit this to both master and dev.

**Comment by mike-anthony** [comment]
Tests seem smooth on my side. Have committed to the dev branch.

Please could you check before I merge to master?

**Comment by tbba** [comment]
Yes the error is gone here! - Thank you for the blazing-fast fix.

**Comment by mike-anthony** [comment]
Any time - glad it works. As mentioned in the support thread, this is not an ideal fix, as the issue only appears in 2.5.3 (and maybe one of the later PW dev versions). As such, a few months after the big 2.6 release, I'm going to make Jumplinks require 2.6.
